### ISSUE TITLE
Ensure compatible CoreProtect version

### ISSUE THREAD

**Issue by rlf** [rlf/XRayHunter#4]
The current plugin relies on non-public code from CoreProtect, so some checks should be introduced to guarantee it will work (i.e. just checking for API version > 2 doesn't cut it, more like querying the methods on the Lookup object).

**Comment by adracamas** [comment]
Yeah.. it's erroring out.

[18:28:30] [Server thread/ERROR]: Could not load 'plugins/XRayHunter.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: CoreProtect
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:287) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:249) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:473) [craftbukkit-1.8.1-20150113a.jar:git-Bukkit-e6f9fd4]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

**Comment by rlf** [comment]
Currently requires 2.10.0 - will try to make it more resilient to night (GMT+1)
